const legacyRoutes: Record<string, string> = {
  about: "/about",
  "admin-add-account": "/admin/accounts",
  "admin-add-service": "/admin/services",
  "admin-add-warehouse": "/admin/inventory",
  "admin-doctor-manage": "/admin/doctors",
  "admin-doctor-records": "/admin/records",
  "admin-doctor-records-add": "/admin/records",
  "admin-doctor-records-detail": "/admin/records",
  "admin-doctor-records-edit": "/admin/records",
  "admin-reception-appointment": "/admin/appointments",
  "admin-reception-confirm": "/admin/appointments",
  "admin-reception-invoice": "/admin/invoices",
  "admin-reception-invoice-add": "/admin/invoices",
  "admin-reception-manage": "/admin/appointments",
  "admin-reception-payment": "/admin/invoices",
  "admin-reception-support": "/admin/support",
  "admin-service-management": "/admin/services",
  "admin-system-account-management": "/admin/accounts",
  "admin-treatment-add": "/admin/treatments",
  "admin-treatment-detail": "/admin/treatments",
  "admin-treatment-manage": "/admin/treatments",
  "admin-update-account": "/admin/accounts",
  "admin-update-service": "/admin/services",
  "admin-update-warehouse": "/admin/inventory",
  "admin-warehouse-management": "/admin/inventory",
  booking: "/booking",
  "confirm-booking": "/confirm-booking",
  contact: "/contact",
  "doctor-management-records": "/admin/treatments",
  "doctor-management-records-add": "/admin/treatments",
  "doctor-management-records-detail": "/admin/treatments",
  "doctor-profile": "/profile",
  "doctor-record-add": "/admin/records",
  "doctor-record-detail": "/admin/records",
  "doctor-record-edit": "/admin/records",
  "doctor-records": "/admin/records",
  home: "/",
  index: "/",
  login: "/login",
  manage: "/manage",
  profile: "/profile",
  pro5: "/pro5",
  "reception-invoice": "/admin/invoices",
  "reception-invoice-create": "/admin/invoices",
  "reception-manage": "/admin/appointments",
  "reception-payment": "/admin/invoices",
  "reception-profile": "/profile",
  "reception-support": "/admin/support",
  reset: "/reset",
  "reset-new": "/reset-new",
  "reset-otp": "/reset-otp",
};

export function getLegacyRoute(slug: string) {
  const normalized = decodeURIComponent(slug).replace(/\.html$/i, "");
  return legacyRoutes[normalized];
}
